apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: myrs
spec:   
 replicas: 3
 selector:
  matchLabels:
   type: webserver
   author: joe
 template:
  metadata:
   name: mypod
   labels:
    type: webserver
    author: joe
  spec:
   containers:
    - name: c1
      image: nginx
